### ISSUE TITLE
v4: fetch object by id not working

### ISSUE THREAD

**Issue by SavvasMohito** [weaviate/weaviate-python-client#706] opened 2024-01-05 16:47 UTC
Hi there, I have been using the v4 client on version 4.4b6 along with the latest server version 1.23.1. I noticed that `collection.query.fetch_object_by_id(uuid)` is not working. It probably has to do with the new functions added for v1.23 [here](https://github.com/weaviate/weaviate-python-client/blob/bd215a950dda619988b0e25a6ca56110241331a0/weaviate/collections/queries/fetch_object_by_id.py#L146), because the HTTP endpoint is working correctly. There is no error coming back when performing the function, it just doesn't return something back.

**Comment by tsmith023** [comment] 2024-01-05 16:53
What is the specific error that you are seeing when you use the method?

**Comment by SavvasMohito** [comment] 2024-01-05 16:59
I am not seeing any error, I just get an empty result. I know for a fact that the ID I am trying to fetch exists, I can normally retrieve it using the HTTP API.

**Comment by tsmith023** [comment] 2024-01-05 17:27
There's a decently large amount of use of `fetch_object_by_id` in our integration tests for the v4 client! Would you be able to post a Minimum Reproducible Example (MRE) of your client/collection/Weaviate configuration that replicates the issue that you're seeing?

**Comment by SavvasMohito** [comment] 2024-01-05 22:58
I just tested out creating a dummy collection, adding an object to it and then using `fetch_object_by_id` which worked correctly. The issue still occurs when trying to `fetch_object_by_id` from my existing collections though, which were created with older versions of the client and Weaviate.

My weaviate configuration
```yaml
version: '3.9'

services:
  weaviate:
    container_name: weaviate
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
      - --read-timeout=300s
      - --write-timeout=300s
    image: semitechnologies/weaviate:1.23.1
    ports:
      - 8080:8080
      - 50051:50051
    volumes:
      - /home/ubuntu/weaviate/var/weaviate:/var/lib/weaviate
      - /home/ubuntu/weaviate/backups:/var/lib/backups
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'  
      BACKUP_FILESYSTEM_PATH: '/var/lib/backups'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-openai'
      ENABLE_MODULES: text2vec-openai, backup-filesystem
      CLUSTER_HOSTNAME: 'node1'
      OPENAI_APIKEY: ${OPENAI_API_KEY}
      LIMIT_RESOURCES: true
```

client configuration
```python
import weaviate
client = weaviate.connect_to_local(host="10.68.XXX.XX")
collection = client.collections.get("debug")
collection.query.fetch_object_by_id('dc93bf76-0a22-47b4-81c4-6e153d815e9f')
```

collection setup
```python
weaviate_client.collections.create(
        name="debug",
        description="",
        vectorizer_config=wvc.Configure.Vectorizer.text2vec_openai(),
        properties=[
            wvc.Property(name="description", data_type=wvc.DataType.TEXT),
            wvc.Property(name="outcomeid", data_type=wvc.DataType.TEXT, skip_vectorization=True),
            wvc.Property(name="companyName", data_type=wvc.DataType.TEXT, skip_vectorization=True),
            # Optional
            wvc.Property(name="url", data_type=wvc.DataType.TEXT, skip_vectorization=True),
            wvc.Property(name="impact", data_type=wvc.DataType.TEXT),
            wvc.Property(name="website", data_type=wvc.DataType.TEXT, skip_vectorization=True),
            wvc.Property(name="yearEstablished", data_type=wvc.DataType.TEXT, skip_vectorization=True)
        ],
    )
```

**Comment by dirkkul** [comment] 2024-01-06 04:57
I think this is a weaviate error and the inverted index of your collection might be corrupted.

Could you go to your console and try the following in GQL?
```
{
  Get {
    Article(where: {
      path: ["id"],
      operator: Equal,
      valueText: "00037775-1432-35e5-bc59-443baaef7d80". <= replace with your ID
    }) {
      description
    }
  }
}
```

**Comment by SavvasMohito** [comment] 2024-01-06 15:55
Hi @dirkkul, thanks for your suggestion. The console returns an empty result too for my existing collections, but it works correctly once I try it on the dummy collection I created yesterday. It appears to have the same behaviour as the client, so I assume this means that something has happened to my weaviate instance.

```graphql
{
  "data": {
    "Get": {
      "My_collection": []
    }
  }
}
```

**Comment by dirkkul** [comment] 2024-01-07 07:04
yeah, looks like the inverted index got corrupted :(

Can you check your logs if you see anything? But it might be easier to reimport the class, I hope it is not too big. Here is a script in how to do it: https://weaviate.io/developers/weaviate/manage-data/migrate

**Comment by SavvasMohito** [comment] 2024-01-07 21:07
Thanks for the suggestion @dirkkul. Do you think a backup and restore would work for this or is migration a better option?

**Comment by dirkkul** [comment] 2024-01-08 04:38
> Do you think a backup and restore would work for this

not 100% sure, but I don't think so - AFAIK the backup is just copying files so you would just copy any corrupted index. But feel free to give it a try

**Comment by SavvasMohito** [comment] 2024-01-08 15:48
You were probably right about the index being corrupted @dirkkul. I migrated the data to a new instance and fetching by id seems to work fine now. I was not able to transfer the cross-references though, not sure about that. Thankfully they are not too hard to re-do. Could it be because of the new structure of weaviate separating the references from the properties?

**Comment by dirkkul** [comment] 2024-01-08 16:32
> Could it be because of the new structure of weaviate separating the references from the properties?

No, that is purely a client-side change. I sadly do not know why that happened - you can make an issue in the main weaviate repo if you want, but without any logs it is hard to pinpoint.

>  I was not able to transfer the cross-references though, not sure about that.

oh bummer, why didn't that work?

**Comment by dirkkul** [comment] 2024-01-11 09:11
I assume your reference problem was casued by [this](https://github.com/weaviate/weaviate-python-client/issues/714)? :)

I'm closing this issue, please just open a new one if there are further issues

**Closed by dirkkul** 2024-01-11 09:11 UTC
Labels: v4-beta
