### ISSUE TITLE
SSL issue when querying the DB

### ISSUE THREAD

**Issue by mick-zelta** [weaviate/weaviate-python-client#519] opened 2023-09-14 14:34 UTC
Anyone ever get SSL errors when using ? I have my python backend containers deployed on kubernetes, using EKS. Everything else works fine but get some SSL errors when trying to query my weaviate instance. Stack trace :

```
ERROR:Unexpected error with Weaviate: Query was not successful.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 461, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/http/client.py", line 1378, in getresponse
    response.begin()
  File "/usr/local/lib/python3.11/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 461, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/http/client.py", line 1378, in getresponse
    response.begin()
  File "/usr/local/lib/python3.11/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/weaviate/gql/filter.py", line 121, in do
    response = self._connection.post(path="/graphql", weaviate_object={"query": query})
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/weaviate/connect/connection.py", line 455, in post
    return self._session.post(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/modules/<my file>", line 472, in query_weaviate
    .do()
     ^^^^
  File "/usr/local/lib/python3.11/site-packages/weaviate/gql/get.py", line 1903, in do
    return super().do()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/weaviate/gql/filter.py", line 123, in do
    raise RequestsConnectionError("Query was not successful.") from conn_err
requests.exceptions.ConnectionError: Query was not successful.
```

Sometimes it works fine - other times it gives an error. For this reason I suspect its something to do with the network (e.g. my AWS Load Balancer), or other config related to how the application is hosted (no. of requests etc.), but I just want to see have others experienced anything similar when using Weaviate.

**Comment by si3mshady** [comment] 2023-12-10 21:52
I've got something similar - Im running weaviate container and im trying to connect to preform a similarity search 

[nltk_data] Error loading punkt: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed:
[nltk_data]     unable to get local issuer certificate (_ssl.c:997)>
connected
[nltk_data] Error loading punkt: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed:
[nltk_data]     unable to get local issuer certificate (_ssl.c:997)>
Attention is a mechanism used in sequence transduction models that connects an encoder and a decoder. It is based on complex recurrent or convolutional neural networks and is used to improve the performance of these models. In the context of the paper, the authors propose a new network architecture called the Transformer, which is based solely on attention mechanisms and does not use recurrence or convolutions. The Transformer model achieves superior quality in machine translation tasks while being more parallelizable and requiring less training time compared to existing models.
Exception ignored in: <function _ClientBase.__del__ at 0x112086b00>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/weaviate/client.py", line 170, in __del__
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/weaviate/connect/connection.py", line 468, in close
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/sessions.py", line 799, in close
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/adapters.py", line 366, in close
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/poolmanager.py", line 222, in clear
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/_collections.py", line 95, in clear
TypeError: 'NoneType' object is not callable

**Comment by si3mshady** [comment] 2023-12-10 21:52
docker run -d \
  --name weaviate \
  -p 8080:8080 \
  -p 50051:50051 \
  -v weaviate_data:/var/lib/weaviate \
  --restart on-failure:0 \
  -e QUERY_DEFAULTS_LIMIT=25 \
  -e AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true \
  -e PERSISTENCE_DATA_PATH='/var/lib/weaviate' \
  -e DEFAULT_VECTORIZER_MODULE='none' \
  -e ENABLE_MODULES='text2vec-cohere,text2vec-huggingface,text2vec-palm,text2vec-openai,generative-openai,generative-cohere,generative-palm,ref2vec-centroid,reranker-cohere,qna-openai' \
  -e CLUSTER_HOSTNAME='node1' \
  semitechnologies/weaviate:1.22.6 \
  --host 0.0.0.0 \
  --port '8080' \
  --scheme http

**Comment by dirkkul** [comment] 2023-12-11 04:23
I don't think that this is a client issue but I sadly don't have an idea on how to fix this.  think our [community forum](https://forum.weaviate.io/) or slack are better places to ask.

I will close this, but please open a new issue in case it is caused by the client

**Closed by dirkkul** 2023-12-11 04:23 UTC

**Comment by cybernagle** [comment] 2024-04-12 07:55
We encountered the same issue where the client was unable to querying data because of self-signed certificate. This problem has been resolved by setting two environment variables:

```
os.environ["GRPC_DEFAULT_SSL_ROOTS_FILE_PATH"] = "/path/to/your/cert.crt"
os.environ["SSL_CERT_FILE"] = "/path/to/your/cert.crt"
```

The reason for using both environment variables is that the version 4 of the Weaviate client utilizes both HTTPX and gRPC for communication. Therefore, we need to specify these two environment variables to inform HTTPX and gRPC of the self-signed certificate's location.

**Comment by shaunak-cisco** [comment] 2024-04-23 01:45
@mick-zelta, were you able to find a solution for your issue? We are running in a similar environment and are seeing the same underlying error as you: `Remote end closed connection without response`

**Comment by mick-zelta** [comment] 2024-04-23 12:55
> @mick-zelta, were you able to find a solution for your issue? We are running in a similar environment and are seeing the same underlying error as you: `Remote end closed connection without response`

Our issue was where our containers were hosted. So we seen this issue when our weaviate instance was in the USA, but our backend configs were hosted in Europe. All is working fine now once we moved all our backend infrastructure to the US @shaunak-cisco
