### ISSUE TITLE
`fetch_objects()` not returning as expected when neither `return_metadata` nor `return_properties` are provided.

### ISSUE THREAD

**Issue by axeloh** [weaviate/weaviate-python-client#607] opened 2023-11-19 12:55 UTC
### This issue applies to the Python v4 client ( `weaviate-client==4.3b2`)

The docstring of the `fetch_objects()` method in `weaviate/collections/queries/fetch_objects.py` states that: 
```python
"""
NOTE:
    If neither `return_metadata` nor `return_properties` are provided then all properties and metadata are returned except for `metadata.vector`.
"""
```
However, this seem not to be the case.   
Rather, none of them are returned.

--------- 
#### :white_check_mark: Example 1 (works as expected):
- `fetch_objects()` called with providing `return_properties=['chunk_id, 'text']`.
![image](https://github.com/weaviate/weaviate-python-client/assets/32063225/af4cc1d1-1d23-4a56-9df0-886b7983a7dc)

--------- 
#### :x: Example 2 (does not work as expected):
- `fetch_objects()` called without providing anything.
![image](https://github.com/weaviate/weaviate-python-client/assets/32063225/069a3bdf-f768-42c3-9074-fc408378c686)

**Comment by tsmith023** [comment] 2023-11-22 09:06
Hi @axeloh, thanks for flagging this inconsistency between the docs and the implementation! This behaviour was indeed changed with the latest version so I will update the docs accordingly.

The intended behaviour is now as follows:
- If no `return_properties` then return all properties
- If no `return_metadata` then return no metadata
- Always return the `UUID` of the objects
- If `include_vector=True` then return the vector of the objects else don't

One of the key aspects in this update is that your Weaviate version must also be bumped accordingly. This is because the logic for returning all the properties if `return_properties=None` must be implemented server-side (the client has no way of knowing what properties there are in a class without first querying the schema). If you bump your Weaviate minor version then Example 2 should work as I have described above!

Cheers 😁

**Comment by kylrth** [comment] 2023-11-29 13:24
Just to clarify for others, I was seeing this behavior using `weaviate-client==4.3b2` with Weaviate 1.22.3, but no longer with Weaviate 1.22.5.

**Comment by dirkkul** [comment] 2023-12-20 12:45
Unless I am missunderstanding something, this should be fixed. Please open a new issue in case it is not :)

**Closed by dirkkul** 2023-12-20 12:45 UTC
Labels: v4-beta
