### ISSUE TITLE
Schema error when ingesting documents

### ISSUE THREAD

**Issue by nextaiarnav** [weaviate/weaviate-python-client#600] opened 2023-11-02 05:34 UTC
The error 
{'error': [{'message': "'id' is a reserved property name, no such prop with name 'id' found in class 'LangChain_14ee2519c3154dcb9ea3f47a8967d0e8' in the schema. Check your schema files for which properties in this class are available"}]}

loader = ConfluenceLoader(
    url="URL", username="USERNAME", api_key="API_KEY")
documents = loader.load(space_key="SPACE_KEY", include_attachments=True, limit=150)
text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=0)
documents = text_splitter.split_documents(documents)
db = Weaviate.from_documents(documents, embeddings, client=client, by_text=False)
chatbot = RetrievalQA.from_chain_type(
   llm=llm,
    chain_type="stuff",
    retriever=db.as_retriever(search_type="similarity",search_kwargs={"k": 1}),
)
prompt = PromptTemplate(template=template, input_variables=["query"])
import sys
while True:
        message=input("prompt: ")
        if message=='exit':
                print('Exiting')
                sys.exit()
        if message=='':
                continue
        response = chatbot.run(prompt.format(query=message))

**Comment by tsmith023** [comment] 2023-11-02 09:05
Hi @nextaiarnav, this error seems to be caused by usage with the LangChain library. You're probably better of posting this issue there in the hope that whomever worked on the LangChain -> Weaviate integration can help you!

**Comment by nextaiarnav** [comment] 2023-11-02 10:20
Okay, thanks!

**Comment by tsmith023** [comment] 2023-11-02 14:19
I will close this for now but feel free to re-open it if you are re-directed back here by the LangChain devs!

**Closed by tsmith023** 2023-11-02 14:19 UTC
